### ISSUE TITLE
Regularization

### ISSUE THREAD

**Issue by boborbt** [ahwillia/NonNegLeastSquares.jl#21]
Hi! 
I was wondering if there is any way to specify a regularization term to the solver.

Thanks in advance.

**Comment by MatFi** [comment]
Not an expert and ask just for curiosity, I usually add up the regularization to the matrix: `A = vcat(A, α * I(size(A,2)))` , is this a bad idea?

**Comment by JeffFessler** [comment]
That's an excellent way to add Tikhonov regularization.
For 1-norm (ℓ₁) regularization, it becomes the LASSO problem that requires different algorithms.
My favorite is POGM with restart:
https://github.com/JeffFessler/MIRT.jl/blob/master/src/algorithm/general/pogm_restart.jl
http://doi.org/10.1007/s10957-018-1287-4

@MatFi I think we can close this issue because you have addressed it.
@boborbt Please reopen if these answers did not address the kind of regularization you had in mind.
